default: &default
  DB_NAME: "google_scraper_ruby"
  DB_HOST: "localhost"
  DB_PORT: "5432"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"
  MAILER_DEFAULT_HOST: "localhost"
  MAILER_DEFAULT_PORT: "3000"
  MAILER_SENDER: "Test <noreply@nimblehq.co>"
  AVAILABLE_LOCALES: "en"
  DEFAULT_LOCALE: "en"
  FALLBACK_LOCALES: "en"

development:
  <<: *default
  DEVISE_SECRET_KEY: "6a8b67c33f0cd9be1a41ab9989bcceeb1cc46916dc494b105092513efb8c7d2e3c5fc04bd88b6fc0163c0dcbc141a5e65effbfe78fc65090a5cf4fcaf06179b9"

test:
  <<: *default
  TEST_RETRY: "0"

# Set environment variables required in the initializers in order to precompile the assets.
# Because it initializes the app, so all variables need to exist in the Docker build stage (used in bin/docker-assets-precompile).
docker_build:
  <<: *default
  SECRET_KEY_BASE: dummy_secret_key_base
